### ISSUE TITLE
Lesson 6: Video 19 The Branching Factor calculation wrong

### ISSUE THREAD

**Issue by ogarai** [udacity/aind-issue-reports#100]
We started with 25 levels. The first 2 have factors 25 and 24. The last 12 factors decrease from 12 to 1. So in between those there should be 25-2-12 = 11 levels with an average branch factor of 12.

So the estimate should be 25 x 24 x 12^11 x 5 x 10^8

But in the video it is shown as 25 x 24 x 12^13 x 5 x 10^8

The former indeed matches the 3 x 10^23 value.

**Comment by cgearhart** [comment]
Added a text atom to the video explaining the error and the resolution.  Thanks!
