### ISSUE TITLE
Term2 CNN Project it says human_detector instead of dog_detector

### ISSUE THREAD

**Issue by letyrodridc** [udacity/aind-issue-reports#105]
In the quote:

"You are welcome to write your own functions for detecting humans and dogs in images, but feel free to use the face_detector and human_detector functions developed above. You are required to use your CNN from Step 5 to predict dog breed."

There is no human_detector function in project. I think it means dog_detector.

**Comment by cgearhart** [comment]
Looks like it was resolved in commit ce359c5
