### ISSUE TITLE
Term 2 Lesson 2 Part 29 Missing instructor comments for training neural network

### ISSUE THREAD

**Issue by ltfschoen** [udacity/aind-issue-reports#107]
The [fourth video shown in Part 29 at 4:08](https://youtu.be/0EoRxu3EeGM?t=4m8s) they say "this is something we've calculated below in instructor comments", but I can't see any instructor comments below in Part 29. Are they referring to instructor comments in Lesson 2 Part 21, or are the instructor comments they are referring to missing?

**Comment by luisguiserrano** [comment]
Thanks! Fixed.
