### ISSUE TITLE
Term 2 - 30 Keras - error import python

### ISSUE THREAD

**Issue by letyrodridc** [udacity/aind-issue-reports#108]
First at all this is no a bug, The code is working! 

It seems that the last version of Keras 0.10 is not compatible with 0.9. 

It's not big deal but maybe in a future a change is needed in code. 

This is the full post: https://discussions.udacity.com/t/lesson-2-part-30-keras-tensorflow-python-vs-tensorflow-python-io/269178

**Comment by letyrodridc** [comment]
Btw TF is in version 1.1 and they never fixed the backwards compatibility, so it should be change if we want to use the latest versions.

**Comment by cgearhart** [comment]
Added note on version differences to classroom code (updating classroom tf lib version may break other projects across NDs).
