### ISSUE TITLE
Term 2 - MiniProject Student Admision environment aind-dl-mac-linux.yml doesn't seems complete

### ISSUE THREAD

**Issue by letyrodridc** [udacity/aind-issue-reports#109]
There are two students having the same missing packages in installation. Maybe, they should be included in the environment:

NoPackagesFoundError: Packages missing in current linux-64 channels: 
- appnope 0.1.0 py35_0
- appscript 1.0.1 py35_0
- python.app 1.2 py35_4
- xlwings 0.10.2 py35_0

**Comment by letyrodridc** [comment]
In windows file, the students are reporting: "another problem is that panda package is missing in windows environment file"

**Comment by atejeda** [comment]
Any update on this?, thanks.

**Comment by cgearhart** [comment]
This issue should be resolved with the latest commit: [95e3ee3](https://github.com/udacity/aind2-dl/commit/95e3ee3d88a03a578c33f7c7b51cf456808cdffa)
