### ISSUE TITLE
Sim. Annealing ipynb: Specify Euclidean Distance

### ISSUE THREAD

**Issue by hoxiea** [udacity/aind-issue-reports#110]
The AIND-Simulated_Annealing Jupyter notebook doesn't seem to specify that the student should start with Euclidean distance, or that the test cases are checking for Euclidean distance. The closest mention is at the very end in the Optional section: "Use a different distance metric for get_value (e.g., we used the L2-norm (Euclidean distance)"

**Comment by cgearhart** [comment]
Added explicit reference to the Euclidean metric and updated the notebook.
