### ISSUE TITLE
Hill climbing quiz 2

### ISSUE THREAD

**Issue by raphey** [udacity/aind-issue-reports#115]
This quiz suffers from a standard problem in the AIND lectures--they ask a question with a key detail (in this case, step size 2), and the detail is not presented within the quiz question. This is similar to how the map wasn't shown in the search lectures at times when it was necessary. The quiz frame in this should have the step size shown.

**Comment by letyrodridc** [comment]
Students requested X frame step lines in forums: https://discussions.udacity.com/t/video-11-hill-climbing-quiz-spoiler/298411/5

**Comment by cgearhart** [comment]
Annotated quiz node with a note specifying the step size.
