### ISSUE TITLE
Term 2 Lesson 3 Part 7 Simple Recursive Examples

### ISSUE THREAD

**Issue by ltfschoen** [udacity/aind-issue-reports#119]
In this [video at 3:43](https://youtu.be/KN_dRCy3rtw?t=3m43s) it should be `S3 = 0.4 * MAX(0, 1 + S1 - 0.1 * S2)` instead of `S3 = 0.4 * MAX(0.1 + S1 - 0.1 * S3)` (i.e. S3 is linear combo of S1 and S2, not S1 and S3 itself, and a comma between the 0 and the rest of what is inside the brackets, instead of two 0.1 values).

**Comment by cgearhart** [comment]
This lesson will be deprecated soon.
