### ISSUE TITLE
Project 2 explantion

### ISSUE THREAD

**Issue by korakot** [udacity/aind-issue-reports#12]
build-a-game-playing-agent/README.md

The last paragraph is a single very long confusing sentence. Please rewrite it in a simpler way. 

### Tournament

The `tournament.py` script will run a round-robin tournament between your CustomPlayer agent with itertive deepening and your custom heuristic function against several calibrated agent configurations using fixed-depth minimax and alpha-beta search with the example heuristics provided in `sample_players.py`.

**Comment by dhruvp** [comment]
@cgearhart would you mind tweaking the wording please?

**Comment by cgearhart** [comment]
Resolved in commit [5f9e831](https://github.com/udacity/AIND-Isolation/commit/5f9e831ca4969a602ade1866936f611398de91c3)
