### ISSUE TITLE
AIND Incorrect output for solution in eliminate quiz

### ISSUE THREAD

**Issue by elanmi** [udacity/aind-issue-reports#121]
In Lesson 3.5 existing solution (tab solution.py) in elimination quiz produces incorrect output: after running solution for elimination quiz, multiple boxes have more possible values than before running elimination (example: c3, d4, f6, d7,  g4, g6)

**Comment by elanmi** [comment]
![Capture50.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5952abafacd685001f44d0d4/125516c66e82c728ace21e0d46cb958a379791acdab9fd0fe64de29b234324676b5ee17e28ddb17de91423575d0946ac13595c44fdf98d79a4b23d62964e49bc8f3900299f7744eeaa880dbc00b0218f468db3b58a4ac8ed3924e499c2.JPG)
![Capture51.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5952abafacd685001f44d0d4/125516c66e82c728ace21e0d46cb958a379791acdab8fd0fe64de29b234324676b5ee17e28ddb17de91423575d0946ac13595c44fdf98d79a4b23d62964e49bc8f3900299f7744eeaa880dbd07b0218f468db3b58a4ac8ed3927e399c2.JPG)

**Comment by cgearhart** [comment]
The test code was running a different test case. But that seems confusing, so I switched it to run the puzzle shown in the lesson.
