### ISSUE TITLE
Term 2 Lesson 3 Part 24 - Interesting twists

### ISSUE THREAD

**Issue by ltfschoen** [udacity/aind-issue-reports#127]
In this [video at 1:21](https://youtu.be/Xf1oAaTd42w?t=1m21s) the equations shown should be `(0, 1 + S1 - 0.1 * S2)` instead of `(0, 1 + S1 0.1 * S2)` (i.e. missing minus signs)

And in the same [video at 2:24](https://youtu.be/Xf1oAaTd42w?t=2m24s) the Label in the graph should say `Generative Fit` instead of `Generic Fit` to be consistent with previous videos

**Comment by cgearhart** [comment]
This lesson will soon be deprecated.
