### ISSUE TITLE
You have met the global quota for the system

### ISSUE THREAD

**Issue by jdesesquelles** [udacity/aind-issue-reports#130]

**Comment by jdesesquelles** [comment]
As an Artificial Intelligence Nanodegree Student, 
I tried to submit my work using the command line tool "$udacity submit isolation". 

It seems like I have reached the quota on your server. I had this error message: "You have met the global quota for the system"

Would help me please ? let me know if you need more information.
Cheers

**Comment by cgearhart** [comment]
Hey! The "global quota" is a web request limit imposed by the webserver hosting the PA. It is set to 5 submissions in 5 minutes. If you see that error then you should be able to submit again after a short wait.
