### ISSUE TITLE
Term 2 - RNN Project: The time series seems to be normalized between [-1,1], and not between [0,1] as the project's notebook states.

### ISSUE THREAD

**Issue by jganzabal** [udacity/aind-issue-reports#136]
In the RNN project:
Just a simple typo or detail: The time series seems to be normalized between [-1,1], and not between [0,1] as the project's notebook states.

**Comment by letyrodridc** [comment]
Hi @jganzabal Thanks for reporting this. I will merge this ticket with https://github.com/udacity/aind-issue-reports/issues/196 . Close.
