### ISSUE TITLE
Term 2 - Project RNN: window_transform_series tests

### ISSUE THREAD

**Issue by jganzabal** [udacity/aind-issue-reports#137]
Just a simple bug when calculating window_transform_series in RNN time series project. Here is the discussion:
https://discussions.udacity.com/t/wrong-test-in-beginning-of-rnn-project/303464

**Comment by letyrodridc** [comment]
Thanks @jganzabal  for reporting this.

**Comment by cgearhart** [comment]
This project will be deprecated in 2018. This issue will be addressed if there are any minor updates pushed before then.
