### ISSUE TITLE
Term 2 - Lesson 2 - 14 Softmax - Solution improvement

### ISSUE THREAD

**Issue by miguelusque** [udacity/aind-issue-reports#145]

**Comment by miguelusque** [comment]
Hi!

    May I suggest the following code as an improvement of the existing solution?

Before (existing solution):
   import numpy as np

   def softmax(L):
       expL = np.exp(L)
       sumExpL = sum(expL)
       result = []
       for i in expL:
           result.append(i*1.0/sumExpL)
       return result

After (my proposal):
   import numpy as np

   def softmax(L):
       expL = np.exp(L)

       return np.divide (expL, expL.sum())


Hope it helps!

Miguel Ángel

**Comment by miguelusque** [comment]
(sorry for the indent)

**Comment by luisguiserrano** [comment]
Thanks! Added both solutions, for clarity.
