### ISSUE TITLE
Isolation Board.print_board()

### ISSUE THREAD

**Issue by korakot** [udacity/aind-issue-reports#15]
If the board is created but no first moves yet, you can't print it now, because it check for last moves. Students will get confused by why can't they print it out to check.

I suggest put the problematic part inside try-except.

        try:
            p1_r, p1_c = self.__last_player_move__[self.__player_1__]
            p2_r, p2_c = self.__last_player_move__[self.__player_2__]
        except: # not first move yet
            p1_r = p1_c = p2_r = p2_c = -1

**Comment by dhruvp** [comment]
@cgearhart mind taking a look at this as well?

**Comment by cgearhart** [comment]
Fixed in commit [c3cdfd5](https://github.com/udacity/AIND-Isolation/commit/c3cdfd59fc1e0a8982ef0ac6810a1dd9358f174b).
