### ISSUE TITLE
Placeholder in CV_Capstone

### ISSUE THREAD

**Issue by HedgehogInDaFog** [udacity/aind-issue-reports#150]
In Step6 of CV Capstone project there is a phrase: 
"Your model is required to attain a validation loss (measured as mean squared error) of at least XYZ. When you have finished training, save your model as an HDF5 file with file path my_model.h5." 
Here "XYZ" is definitely placeholder which should be replaced

**Comment by cgearhart** [comment]
Updated the notebook to definitize the range. (recommend 0.002 as "good" and 0.0015 as "very good").
