### ISSUE TITLE
Broken Link in AIND Recognizer

### ISSUE THREAD

**Issue by hhprogram** [udacity/aind-issue-reports#154]
In the my_model_selectors.py file for the AIND Recognizer project the link provided in the comments of class SelectorDIC is broken: see:

http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.58.6208&rep=rep1&type=pdf

There are other links that seem to work but I'll let the Udacity team decide which one to use

**Comment by cgearhart** [comment]
Thanks for reporting. I'll update the link.
