### ISSUE TITLE
AWS Community AIM needs to be updated

### ISSUE THREAD

**Issue by anselmotalotta** [udacity/aind-issue-reports#155]

**Comment by anselmotalotta** [comment]
As per discussion in https://discussions.udacity.com/t/tenflow-not-running-on-gpu-on-aws/345673/5

Problem:
CUDA drivers are not updated to required version 375.66.0.

Impact:
TensorFlow doesn't take advantage of GPU acceleration.

Temporary Workaround for students:
Update driver on your own instance following instructions at:
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/accelerated-computing-instances.html#install-nvidia-driver

Proposed Long Term Solution:
Update CUDA driver in AIM.

**Comment by letyrodridc** [comment]
Hi @anselmotalotta The classroom was updated to use a new AMI that has GPU configured. Thanks for reporting this.  I will close the ticket.
