### ISSUE TITLE
Setting up environment

### ISSUE THREAD

**Issue by bvdinesh** [udacity/aind-issue-reports#157]
conda env create -f aind-environment-windows.yml is not working throwing an error saying invalid package channels

**Comment by bvdinesh** [comment]
This step is "conda env create -f aind-environment-windows.yml to create the environment."
 this what i ran "conda env create -f E:\Dinesh\Work\AI\aind-environment-windows.yml -name aind"


Also tried conda create -n aind -f E:\Dinesh\Work\AI\aind-environment
-windows.yml

Here is the error details (e:\ProgramData\Anaconda3) E:\Dinesh\Work\AI>conda create --file E:\aind-environ
ment-windows.yml --name aind

CondaFileIOError: 'E:\aind-environment-windows.yml'. [Errno 2] No such file or d
irectory: 'E:\\aind-environment-windows.yml'

Here is the different command which I tried ===============================================
(e:\ProgramData\Anaconda3) E:\Dinesh\Work\AI>conda env create -f E:\aind-environ
ment-windows.yml
Using Anaconda API: https://api.anaconda.org

SpecNotFound: Can't process without a name


(e:\ProgramData\Anaconda3) E:\Dinesh\Work\AI>conda env create -f E:\aind-environ
ment-windows.yml -n aind
Using Anaconda API: https://api.anaconda.org

SpecNotFound: Invalid name, try the format: user/package

anyone??????

**Comment by letyrodridc** [comment]
Hi @bvdinesh Did you find the solution? Could you solve it? 
Please, for getting help reach your classroom mentors or use the discussion forums for this type of questions: https://discussions.udacity.com/c/nd889-intro-sudoku/nd889-anaconda-setup . Waffle is used to report bugs.
