### ISSUE TITLE
Setting up Anaconda environment

### ISSUE THREAD

**Issue by bvdinesh** [udacity/aind-issue-reports#158]
This step is "conda env create -f aind-environment-windows.yml to create the environment."
 this what i ran "conda env create -f E:\Dinesh\Work\AI\aind-environment-windows.yml -name aind"

[9:20] 
Also tried conda create -n aind -f E:\Dinesh\Work\AI\aind-environment
-windows.yml

Here is the error details (e:\ProgramData\Anaconda3) E:\Dinesh\Work\AI>conda create --file E:\aind-environ
ment-windows.yml --name aind

CondaFileIOError: 'E:\aind-environment-windows.yml'. [Errno 2] No such file or d
irectory: 'E:\\aind-environment-windows.yml'

[9:28] 
Here is the different command which I tried ===============================================

(e:\ProgramData\Anaconda3) E:\Dinesh\Work\AI>conda env create -f E:\aind-environ
ment-windows.yml
Using Anaconda API: https://api.anaconda.org

SpecNotFound: Can't process without a name

(e:\ProgramData\Anaconda3) E:\Dinesh\Work\AI>conda env create -f E:\aind-environ
ment-windows.yml -n aind
Using Anaconda API: https://api.anaconda.org

SpecNotFound: Invalid name, try the format: user/package

[9:28] 
anyone??????

**Comment by letyrodridc** [comment]
Duplicated in : https://github.com/udacity/aind-issue-reports/issues/157
