### ISSUE TITLE
Term 2 - Lesson 2 - Project Dog Breed Classifier - 1. CNN Project

### ISSUE THREAD

**Issue by miguelusque** [udacity/aind-issue-reports#163]

**Comment by miguelusque** [comment]
Hi!

In Term 2 - Lesson 2 - Project Dog Breed Classifier - 2. AWS GPU Instance s(Part 2), there is one command that should be changed.

At step 5, the first command tries to  apt-get install unzip:<br>
5. Download and unzip the human dataset:
> sudo apt-get install unzip
wget https://s3-us-west-1.amazonaws.com/udacity-aind/dog-project/lfw.zip; unzip lfw.zip; rm lfw.zip
<br>
Having into consideration that unzip is used in step 4, I would suggest to move that command to the 4th step, amended as follows:
<br>
4. Download and unzip the dog dataset:

> **sudo apt-get install unzip**
> wget https://s3-us-west-1.amazonaws.com/udacity-aind/dog-project/dogImages.zip; unzip dogImages.zip; rm dogImages.zip
<br>
5. Download and unzip the human dataset:

> wget https://s3-us-west-1.amazonaws.com/udacity-aind/dog-project/lfw.zip; unzip lfw.zip; rm lfw.zip

Hope it helps!

Miguel Ángel

**Comment by miguelusque** [comment]
Apologies,

My comments above corresponds to:
Term 2 - Lesson 2 - Project Dog Breed Classifier - 1. CNN Project

Sorry about the inconveniences

Miguel Ángel

**Comment by alexisbcook** [comment]
Great catch, and thanks for the feedback!  The newest version of the README leaves it up to the student to determine for herself/himself the best way to unzip the datasets.
