### ISSUE TITLE
Term 2 - Lesson 2 - Project Dog Breed Classifier - Error in proposed model image

### ISSUE THREAD

**Issue by miguelusque** [udacity/aind-issue-reports#165]

**Comment by miguelusque** [comment]
Hi,

At Term2 - Lesson 2 - Project Dog Breed Classifier, I have noticed that there is a mistake in the model proposed as a hint to the student.

Please notice that in the image below, the first layer has input size of 223x223, which suggest that the image size is 223x223. 

Based on the existing code in the jupyter notebook, the correct input image size is 224x224.

![sample_cnn.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58f33815592878001a1e63aa/125516c66e82c728ace21e0d46fb9597338e86968ce7b101e81fe086264c22703d46f96925ddbb7aea142d59595d18a4410a5e47fcf8892ff4b43871984019af80330b2b9b645bf9fa9015ad00bd2a8a4a85b3bf8c4fc8e83a24e08b9d02.png)

Hope it helps,

Have a udacious day!

Miguel Ángel

**Comment by alexisbcook** [comment]
Note that the code says "Output Shape", not "Input Shape"!

The first (input) layer has a size of 224 x 224 x 3.  (This is not shown in the code above.)
223 x 223 x 16 refers to the size of the convolutional layer (which is the second layer of the network).
