### ISSUE TITLE
AWS p2.xlarge

### ISSUE THREAD

**Issue by letyrodridc** [udacity/aind-issue-reports#166]
The following lesson is duplicated in Dog Breed and CNN 
In Dog Breed: https://classroom.udacity.com/nanodegrees/nd889/parts/16cf5df5-73f0-4afa-93a9-de5974257236/modules/53b2a19e-4e29-4ae7-aaf2-33d195dbdeba/lessons/2df3b94c-4f09-476a-8397-e8841b147f84/concepts/ced1fa22-5723-4212-b73f-08f7f6613cae

In CNN:
https://classroom.udacity.com/nanodegrees/nd889/parts/16cf5df5-73f0-4afa-93a9-de5974257236/modules/53b2a19e-4e29-4ae7-aaf2-33d195dbdeba/lessons/37492b45-ee34-4dc3-a2e8-076149f92562/concepts/ced1fa22-5723-4212-b73f-08f7f6613cae

I'm sure that one of the lessons suggested the use of g2.xlarge instead of p2.xlarge. I don't know if that was changed or it is missed.

**Comment by cgearhart** [comment]
The lesson has been removed from the dog breed project.
