### ISSUE TITLE
DNN: Concept 21: Multi-class Cross Entropy - incorrect variables on doors?

### ISSUE THREAD

**Issue by clapollo** [udacity/aind-issue-reports#167]
One of my mentee's pointed this out: around 2:07 in the video, three doors appear, labeled i, j, k. However, the sentences Luis is speaking, which are drawn out as pictogram-type statements, all refer to door j. 

So the equations should be something like:

y1j if DUCK_PIC behind door j
y2j if WALRUS_PIC behind door j
y3j if WALRUD_PIC behind door j

**Comment by cgearhart** [comment]
Previously fixed.
