### ISSUE TITLE
aind - intro to gameplaying: #16-coding minimax

### ISSUE THREAD

**Issue by johannesgiorgis** [udacity/aind-issue-reports#171]
i was re-working the code to better understand it. I added a few more lines to 'testcode.py' file to do more testing. Although I could modify it, when clicknig the 'Test Run' button, it proceeded as if the additional lines were never there. Then I tried commenting out the last few lines of code + print statements it already had and re-run it. It still printed out the same things as before. So not only am I not able to add additional lines, commenting out the existing lines had no impact. Is the 'testcode.py' file provided is there just for us to see what the test runs? It is not clear + it would be better if we could modify it. In other lectures, I have been able to modify and play around with it to better understand and debug my code. Thanks!

**Comment by letyrodridc** [comment]
Hi @johannesgiorgis  yes, same happened to me. I issued another ticket. I will keep yours and merge it with mine. Thanks for bringing this to waffle.

**Comment by letyrodridc** [comment]
More information: https://github.com/udacity/aind-issue-reports/issues/188

**Comment by cgearhart** [comment]
I just modified the quiz nodes to import student code for the test case, so you can change that code and see the results. Note that this does NOT change the way the quiz is **scored** -- you will have to pass the test suite hosted on the backend. This change is primarily meant to support debugging & development in the quiz node.

**Comment by johannesgiorgis** [comment]
Thanks Chris!
