### ISSUE TITLE
AIND Term 1: Explanation of alpha-beta pruning is too thin

### ISSUE THREAD

**Issue by mohankarthik** [udacity/aind-issue-reports#174]
I think the explanations of alpha-beta pruning in this module are quite weak. In fact there is no explanation. What are alpha and beta? Without explaining the core algorithm it’s senseless to move on to n-player alpha beta.

Thank God for AIMA and other online resources. Still, I hope the rest of the nanodegree isn’t this hand-wavy.

Refer: https://discussions.udacity.com/t/comment-explanation-of-alpha-beta-pruning-is-too-thin/383607

**Comment by cgearhart** [comment]
Added text node with clarification.
