### ISSUE TITLE
aind2 AMI is broken

### ISSUE THREAD

**Issue by smile-on** [udacity/aind-issue-reports#175]
udacity-aind2-0.0.6 (ami-b5f792d5) has incorrect vertion of cudnn library installed.

Test: ~aind2$ nvidia-smi
Failed to initialize NVML

Fix: You need to install "cuDNN v2 (March 17,2015), for CUDA 6.5" library and update LD_LIBRARY_PATH.

I made slav-aind2-0.0.6 AMI available for you to copy and distribute to the students.
@see forum for more details on issue
https://discussions.udacity.com/t/is-the-aws-instance-actually-using-the-gpu/382546/4

**Comment by cgearhart** [comment]
All project instructions have been migrated to a public deep learning AMI.
