### ISSUE TITLE
AIND T2 Keras Lesson 3.32 solution does not comply with problem

### ISSUE THREAD

**Issue by jg1141** [udacity/aind-issue-reports#179]

**Comment by jg1141** [comment]
On [this page](https://classroom.udacity.com/nanodegrees/nd889/parts/16cf5df5-73f0-4afa-93a9-de5974257236/modules/6124bd95-dec2-44f9-bf3b-498ea57699c7/lessons/47f6c25c-7749-4a02-b807-7a5b37f362e8/concepts/7c3d9b4c-206d-4430-9459-c78357181d9a), the quiz specifies a *tanh* activation and a *binary_crossentropy* loss. The solution reads:
```
# Building the model
xor = Sequential()
xor.add(Dense(32, input_dim=2))
xor.add(Activation("sigmoid"))   <<<<<<<<<< should be tanh
xor.add(Dense(2))
xor.add(Activation("sigmoid"))

xor.compile(loss="categorical_crossentropy", optimizer="adam", metrics = ['accuracy'])  <<<< should be binary
```

**Comment by cgearhart** [comment]
previously fixed
