### ISSUE TITLE
Term 2 - Lesson 8 - 7. Simple recursive example - Video typo

### ISSUE THREAD

**Issue by miguelusque** [udacity/aind-issue-reports#180]

**Comment by miguelusque** [comment]
Hi!

   I think I have found a typo in Term 2 - Lesson 8 - 7. Simple recursive example video.

  At minutes 4:23 and 4:50 there are missing the multiply and closing parentheses signs for the S4 element.

The corrected version would be:
S4 = 0.4 __*__ max(0.1 + S2 - 0.1 __*__ S3 __)__
 
At S3, there is also another typo. It should 0.1 instead of 0,1

https://youtu.be/F4-CBqMsd_Y?t=4m23s
https://youtu.be/F4-CBqMsd_Y?t=4m50s


I hope it helps!

**Comment by miguelusque** [comment]
Hi again,

   My fault! I am wrong a couple of types.

   Please, forget the S3 typo. It is correct!!!

   Also at S4, there is a dot in the max function where it should be a comma.

    S4 = 0.4 * max(0, 1 + S2 - 0.1 * S3 )

My mistake! Sorry about that!!

**Comment by letyrodridc** [comment]
Thanks, @miguelangel for the update.  Verified, typo in S4 = 0.4 * max(0, 1 + S2 - 0.1 * S3 ) on Video https://www.youtube.com/watch?v=F4-CBqMsd_Y&feature=youtu.be&t=4m23s
