### ISSUE TITLE
Confusing message about first optional concentration project

### ISSUE THREAD

**Issue by letyrodridc** [udacity/aind-issue-reports#181]
chapter 9 of lesson 2 (Intro to Voice User Interfaces) tells that I have to wait for the concentration to open before submitting the zip-file.
![image](https://user-images.githubusercontent.com/9123307/31717253-82a3560a-b3e1-11e7-9c9e-e9411d38ebe9.png)

https://classroom.udacity.com/nanodegrees/nd889/parts/16cf5df5-73f0-4afa-93a9-de5974257236/modules/38e74312-3173-4456-919d-bcb00a82bfb5/lessons/dc1efdfd-e07f-4a5c-ab35-dbb274a25c88/concepts/3b6ec641-6ce6-4347-b431-15813c017e9d

**Comment by letyrodridc** [comment]
There is also a Note above that is incorrect.

**Comment by cgearhart** [comment]
Previously fixed.
