### ISSUE TITLE
Gateway Timeout

### ISSUE THREAD

**Issue by tushartuteja** [udacity/aind-issue-reports#182]

**Comment by tushartuteja** [comment]
Getting gateway timeout when I submit code for evaluation in the only choice quiz.
![Screenshot 2017-10-20 19.27.22.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ea011518cdbd00119dbc04/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1c36417773e7b54e37a29cbb17ff1102943434d0eee1e020a17b8eb8339a3be34728f5a0de5d76f097cc66f10afb8831fbb53b8248a5d99a4fedb1294b7607caddecd5d340c041183fe5835a89c4bc059f049e24c56b65e.png)

**Comment by letyrodridc** [comment]
Hi @tushartuteja. Thanks. It seems to be an issue in the service availability.  Could you please try again?

**Comment by cgearhart** [comment]
This was traced to a backend issue that the classroom team has resolved. I'm sorry for the inconvenience.
