### ISSUE TITLE
First exercise  at the end of "Lesson 5- 5.Strategy 1: Elimination"

### ISSUE THREAD

**Issue by cmondorf** [udacity/aind-issue-reports#183]

**Comment by cmondorf** [comment]
A message about something missing is displayed when entering a solution:

![somethingmissing.jpeg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5809e15af002560e00946344/125516c66e82c728ace21e0d46fb9b9726968ba081eeb24ab74ef99a2e046b313916ac217586f76ae5002e59575d4baa47505946aaf18979a7b53c718a5859efd56c4d68d47f40f2ecdd42e64bef62994597b4be804dc5e8352cee828c4b391704189bb2.jpeg)

However, if one actually submits the solution, then it passes:
![thanksforcompleting.jpeg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5809e15af002560e00946344/125516c66e82c728ace21e0d46fc9c9b2d8990af80fbbc4ca94dfc913d4f29746b48e13b628ae92dbc56395b4d5a46a4435d5942f4ff8b7daeb66e71895c0aedd53f5d70c72f0dbefad341eb5ee779c11ac7a4b6984dc8e23c20e7838646371d001e8dfe5d27ed.jpeg)

This suggests there is a discrepancy in how the test run and submission buttons are evaluating solutions.

**Comment by cgearhart** [comment]
Internal ticket #J1830

**Comment by cgearhart** [comment]
The "submit" test was not executing the same test case as the "test" button. It now tests both test cases, so failing the test button will also fail the submit button.
