### ISSUE TITLE
ImportError: No module named ‘tqdm’

### ISSUE THREAD

**Issue by rajLX** [udacity/aind-issue-reports#186]
Started with a fresh EC2 instance as described in described in project overview (https://classroom.udacity.com/nanodegrees/nd889/parts/16cf5df5-73f0-4afa-93a9-de5974257236/modules/53b2a19e-4e29-4ae7-aaf2-33d195dbdeba/lessons/2df3b94c-4f09-476a-8397-e8841b147f84/concepts/e4a523cb-5159-41c7-a1f4-6fae0c476621)

When executing Step 2, I get the following error. I was resisting installing tqdm myself (so that it doesn’t result in a deviate from the standard operating environment for this project). Suggestions?

ImportError Traceback (most recent call last)
in ()
1 from keras.preprocessing import image
----> 2 from tqdm import tqdm
3
4 def path_to_tensor(img_path):
5 # loads RGB image as PIL.Image.Image type

ImportError: No module named ‘tqdm’

**Comment by drewhoskins** [comment]
Me too!

**Comment by drewhoskins** [comment]
https://discussions.udacity.com/t/tqdm-module-not-found/413669/11

**Comment by letyrodridc** [comment]
EC2 AMI has not installed tqdm package used in Dog Breed project.

python3 -m pip install tqdm <-- installation
https://pypi.python.org/pypi/tqdm1 <-- package documentation

**Comment by cgearhart** [comment]
Classroom instructions updated to include this module.
