### ISSUE TITLE
MAX-MAX-MAX quiz not working for me

### ISSUE THREAD

**Issue by shankar-jasti** [udacity/aind-issue-reports#187]

**Comment by shankar-jasti** [comment]
I believe I have entered correct answer. Also verified with answer. When I submitted response says "Try again". Same for previous quiz. I am not sure there is an issue with my id.

**Comment by letyrodridc** [comment]
Hi @shankar-jasti ,
Remember to post first in forums or slack this issues if you didn't. There a mentor can help you to decide if it's a bug or not.  Also, you can consult your classroom mentor.
Could you please share me your solution? I would like to try it in my classroom. Thanks.
