### ISSUE TITLE
Changes in Udacity homepage affecting mini-project text_processing NLP - Brazil

### ISSUE THREAD

**Issue by letyrodridc** [udacity/aind-issue-reports#189]
Udacity homepage is redirecting to Brazilian homepage for some countries like Brazil, Argentina.

The following mini-project:
https://github.com/udacity/AIND-NLP/blob/master/text_processing.ipynb

Stop working because it calls:

```
r = requests.get("https://www.udacity.com/courses/all")
summaries = soup.find_all("div", class_="course-summary-card")

```

But the URL https://www.udacity.com/courses/all redirected to Brazil hasn't the same HTML format. There is no div with "course-summary-card" class.

**Comment by cgearhart** [comment]
Internal ticket created. [J1719]

**Comment by ronny-udacity** [comment]
fixed with commit: 
https://github.com/udacity/AIND-NLP/commit/12a5d0703d334da0b852c53337a71cc221049e27
