### ISSUE TITLE
Add all requested heuristics to isolation tournament.py

### ISSUE THREAD

**Issue by luisatlive** [udacity/aind-issue-reports#19]
chris.gearhart [10:27 AM] 
what @maks said is what we intended.  Any suggestions for stating it more clearly to avoid this confusion?

luis [10:38 AM] 
Easiest way would be to have tournament actually call out three different players with the 3 heuristics… analysis is seeing how the three perform :slightly_smiling_face:

[10:38]  
then write up about that of course

[10:38]  
probably confusing to some to have dead code be part of project submission, but if it’s called then it’s obvious it needs to be implemented

**Comment by cgearhart** [comment]
Additional context: rather than using a single "custom_score" function, require three separate heuristics (e.g., custom_score1/2/3), then construct and test all three players in the tournament file.  This would ensure that all three heuristics have been implemented in the game_agent file.

**Comment by cgearhart** [comment]
Added all heuristics to the tournament.

Example output:
```
                        *************************                         
                             Playing Matches                              
                        *************************                         

 Match #   Opponent    AB_Improved   AB_Custom   AB_Custom_2  AB_Custom_3 
                        Won | Lost   Won | Lost   Won | Lost   Won | Lost 
    1       Random       7  |   3     5  |   5     5  |   5     4  |   6  
    2       MM_Open      5  |   5     7  |   3     1  |   9     0  |  10  
    3      MM_Center     5  |   5     6  |   4     2  |   8     6  |   4  
    4     MM_Improved    8  |   2     6  |   4     0  |  10     1  |   9  
    5       AB_Open      4  |   6     4  |   6     2  |   8     4  |   6  
    6      AB_Center     3  |   7     5  |   5     0  |  10     2  |   8  
    7     AB_Improved    6  |   4     5  |   5     2  |   8     2  |   8  
--------------------------------------------------------------------------
           Win Rate:      54.3%        54.3%        17.1%        27.1%    

```
