### ISSUE TITLE
Lab/Pac-Man: Inconsistent external links

### ISSUE THREAD

**Issue by overtane** [udacity/aind-issue-reports#190]
In the lab page (classroom/search-lesson/lab: pac-man) there are two links to Berkley's CS188, but these are to different version of the course. This is confusing. Also the content of the project zip-file is different - the autograder.py is lacking from the old one (as well as from the zip Udacity distributes). The autograder is very useful and should be included if possible.

**Comment by cgearhart** [comment]
Internal ticket #J1832

**Comment by cgearhart** [comment]
Updated pacman zip & links in classroom.
