### ISSUE TITLE
BookWorm project in AIND(NLP) - Not working in Watson 1.0.0 . The API was updated and some methods deprecated.

### ISSUE THREAD

**Issue by sumchat** [udacity/aind-issue-reports#194]
The existing code is for Watson-developer-cloud 0.26.1. But the version 1.0 has some changes in the API. So the existing code in jupyter notebook does not work anymore.

**Comment by letyrodridc** [comment]
Thanks @sumchat 
Reference this post: https://discussions.udacity.com/t/having-trouble-setting-up-watson/451035/6
Workaround: a Conda environment could be provided to warranty that all students work on 0.26.1 until the Notebook is updated.

**Comment by cgearhart** [comment]
I've updated the classroom instructions to notify students that they should use the old version. We'll update the project with a long-term fix soon.
