### ISSUE TITLE
Link to despicableme in the Term2 LSTM Lesson, part 10 (other architectures)

### ISSUE THREAD

**Issue by atejeda** [udacity/aind-issue-reports#202]
The Steve Carell links points to http://despicableme.wikia.com/wiki/Felonius_Gru

**Comment by letyrodridc** [comment]
haha An easter egg :D As you know, Steve made Gru voice in the movie.

![image](https://user-images.githubusercontent.com/9123307/33959035-0489c9fa-e025-11e7-9e12-c37f513343a9.png)
