### ISSUE TITLE
Dead Link on Intro to Voice User Interface

### ISSUE THREAD

**Issue by handria-ntoanina** [udacity/aind-issue-reports#204]

**Comment by handria-ntoanina** [comment]
The link to the 'Amazon Step-by-step instructions' is not working.
![2017-12-14_163441.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a3367c8c019c80011f0694c/125516c66e82c728ace21e0d46bac4cb74cfd2fbc2b8eb7cf50ba3c07d17653f6b14b1247a80e03cfd18395457574ca9475e5742feaf812bf4b73f708b5c0fbfd3695e66da2f53fde6d640e258f075c95d8fa4bd8d46c1ed3c26e48a874b3a1e011a80ed10.jpg)

![2017-12-14_163510.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a3367c8c019c80011f0694c/125516c66e82c728ace21e0d46bac4cb74cfd2fbc2b8eb7cf50ba3c17816653f6b14b1247a80e03cfd18395457574ca9475e5742feaf812bf4b73f708b5c0fbfd3695e66da2f53fde6d640e258f075c95d8fa4bd8d46c1ed3c26e48a874b3d17001c8fed10.jpg)

**Comment by cgearhart** [comment]
Thanks for reporting. The link has been updated.
