### ISSUE TITLE
RNN Project: "section Accelerating the Training Process below"

### ISSUE THREAD

**Issue by robertcrowe-zz** [udacity/aind-issue-reports#206]

**Comment by robertcrowe-zz** [comment]
https://classroom.udacity.com/nanodegrees/nd889/parts/16cf5df5-73f0-4afa-93a9-de5974257236/modules/9da6b5e3-590a-40b9-bb5b-f67b66ef2930/lessons/7f4f5fcf-14c5-4225-92fd-0dba7a45120d/concepts/60924ae1-5afb-400c-8abd-76f8341cd364

**Comment by robertcrowe-zz** [comment]
The section referred to does not exist

**Comment by cgearhart** [comment]
Thanks -- I've changed the instructions to point to the cloud computing setup lesson to use AWS EC2 GPU support.
