### ISSUE TITLE
AIND January Deadlines empty

### ISSUE THREAD

**Issue by juankikushima** [udacity/aind-issue-reports#207]
No project due dates on the calendar

**Comment by cgearhart** [comment]
Can you provide a link to the calendar?

**Comment by juankikushima** [comment]
It was here
https://calendar.google.com/calendar/embed?src=knowlabs.com_p341c4duep5irvmo76620vpo1k%40group.calendar.google.com&ctz=America%2FLos_Angeles

But it has been updated!

Juan Kikushima
