### ISSUE TITLE
AIND term-1 projects submitted but got an extension

### ISSUE THREAD

**Issue by arfahsaeed** [udacity/aind-issue-reports#209]

**Comment by arfahsaeed** [comment]
I completed all my projects and my classroom page says that I've completed all the requirements for term-1, but this morning I got an email saying that Ive been given an extension till Feb 25th to complete the projects. Can anybody please address the issue?

**Comment by cgearhart** [comment]
Thanks! This issue has been reported to the email team for resolution.
