### ISSUE TITLE
P.2 - research review instruction

### ISSUE THREAD

**Issue by korakot** [udacity/aind-issue-reports#21]
""" Write a simple one page summary of the paper covering the following:
- A brief summary of the paper's goals.
- A brief summary of the paper's results."""

Writing about the goals and results will not cover paper content at all. Most of it is about "how to" achieve a certain goal by novel techniques. Maybe add another bullet about "techniques".

**Comment by danainschool** [comment]
Thank you - we will review the wording on the instruction page

**Comment by cgearhart** [comment]
Updated instructions and rubric. The new instructions say:

> 2. Write a simple one page summary of the paper covering the following:
> - A brief summary of the paper's goals or techniques introduced (if any).
> - A brief summary of the paper's results (if any).
