### ISSUE TITLE
Term 1 - Lesson 4 Section 5 Elimination Feedback Typo

### ISSUE THREAD

**Issue by mtroiani** [udacity/aind-issue-reports#210]
When testing an answer that is incorrect the printed feedback "Input" and "Output" boards are identical-it's printing the output board for both input and output. For example, if one changes every entry in the board to '1' the printed "Input" board contains all '1's. 

Actual input: {'B5': '123456789', 'A8': '123456789', 'H9': '9', 'F1': '123456789', 'E6': '123456789', 'D5': '123456789', 'D3': '8', 'I3': '5', 'D2': '123456789', 'F3': '6', 'I6': '123456789', 'C4': '8', 'F2': '123456789', 'I8': '123456789', 'E7': '123456789', 'A6': '123456789', 'B2': '123456789', 'F6': '8', 'H3': '123456789', 'C3': '1', 'A5': '2', 'I4': '123456789', 'A1': '123456789', 'F8': '123456789', 'B8': '123456789', 'C6': '6', 'A3': '3', 'H8': '123456789', 'G4': '6', 'B7': '123456789', 'B1': '9', 'G6': '9', 'E1': '7', 'C1': '123456789', 'C7': '4', 'G2': '123456789', 'F5': '123456789', 'B4': '3', 'A4': '123456789', 'B3': '123456789', 'E5': '123456789', 'B9': '1', 'G9': '123456789', 'I5': '1', 'E9': '8', 'D7': '9', 'F7': '2', 'E3': '123456789', 'H5': '123456789', 'E2': '123456789', 'E8': '123456789', 'C5': '123456789', 'C2': '123456789', 'A9': '123456789', 'H6': '3', 'G1': '123456789', 'D8': '123456789', 'I9': '123456789', 'G7': '5', 'I7': '3', 'F4': '7', 'I1': '123456789', 'D6': '2', 'G5': '123456789', 'F9': '123456789', 'A2': '123456789', 'D9': '123456789', 'I2': '123456789', 'C8': '123456789', 'E4': '123456789', 'H1': '8', 'H4': '2', 'D1': '123456789', 'H2': '123456789', 'H7': '123456789', 'B6': '5', 'D4': '1', 'A7': '6', 'G8': '123456789', 'C9': '123456789', 'G3': '2'}

Actual Output:
{'B5': '1', 'A8': '1', 'H9': '1', 'F1': '1', 'E6': '1', 'D5': '1', 'D3': '1', 'I3': '1', 'D2': '1', 'F3': '1', 'I6': '1', 'C4': '1', 'F2': '1', 'I8': '1', 'E7': '1', 'A6': '1', 'B2': '1', 'F6': '1', 'H3': '1', 'C3': '1', 'A5': '1', 'I4': '1', 'A1': '1', 'F8': '1', 'B8': '1', 'C6': '1', 'A3': '1', 'H8': '1', 'G4': '1', 'B7': '1', 'B1': '1', 'G6': '1', 'E1': '1', 'C1': '1', 'C7': '1', 'G2': '1', 'F5': '1', 'B4': '1', 'A4': '1', 'B3': '1', 'E5': '1', 'B9': '1', 'G9': '1', 'I5': '1', 'E9': '1', 'D7': '1', 'F7': '1', 'E3': '1', 'H5': '1', 'E2': '1', 'E8': '1', 'C5': '1', 'C2': '1', 'A9': '1', 'H6': '1', 'G1': '1', 'D8': '1', 'I9': '1', 'G7': '1', 'I7': '1', 'F4': '1', 'I1': '1', 'D6': '1', 'G5': '1', 'F9': '1', 'A2': '1', 'D9': '1', 'I2': '1', 'C8': '1', 'E4': '1', 'H1': '1', 'H4': '1', 'D1': '1', 'H2': '1', 'H7': '1', 'B6': '1', 'D4': '1', 'A7': '1', 'G8': '1', 'C9': '1', 'G3': '1'}

Printed results:
Something's missing.
Input grid:
1 1 1 |1 1 1 |1 1 1 
1 1 1 |1 1 1 |1 1 1 
1 1 1 |1 1 1 |1 1 1 
------+------+------
1 1 1 |1 1 1 |1 1 1 
1 1 1 |1 1 1 |1 1 1 
1 1 1 |1 1 1 |1 1 1 
------+------+------
1 1 1 |1 1 1 |1 1 1 
1 1 1 |1 1 1 |1 1 1 
1 1 1 |1 1 1 |1 1 1 

Output grid:
1 1 1 |1 1 1 |1 1 1 
1 1 1 |1 1 1 |1 1 1 
1 1 1 |1 1 1 |1 1 1 
------+------+------
1 1 1 |1 1 1 |1 1 1 
1 1 1 |1 1 1 |1 1 1 
1 1 1 |1 1 1 |1 1 1 
------+------+------
1 1 1 |1 1 1 |1 1 1 
1 1 1 |1 1 1 |1 1 1 
1 1 1 |1 1 1 |1 1 1

**Comment by cgearhart** [comment]
Yikes! I just fixed it -- turns out that mutable objects aren't immutable... ;-)
