### ISSUE TITLE
Lesson 7 Step 9

### ISSUE THREAD

**Issue by hhprogram** [udacity/aind-issue-reports#212]
Student seems to pass all tests but still gets an overall error with their code submission.
Below are all the tests the student passed:
(1) Creating empty game board
(2) Getting initial legal moves for player 1
(3) Applying move (0,0) for player 1
(4) Getting initial legal moves for player 2
(5) Applying moves (0,0) for player 1 and (1,1) for player 2
(6) Getting legal moves for player 1 after applying moves (0,0) for player 1 and (1,1) for player 2
(7) Getting legal moves for player 1 after applying moves (0,0) for player 1 and (1,0) for player 2

There is nothing saying they don't pass any tests. But then it says "Look like you still have errors to correct." at the very end.

**Comment by cgearhart** [comment]
Resolved.
