### ISSUE TITLE
Pacman Search Py3 Compatibility

### ISSUE THREAD

**Issue by cgearhart** [udacity/aind-issue-reports#219]
pacman.py libraries not compatible with python3

```Pacman search lab I am having problem with tkinter using Python 3.54 (aind) C:\Udacity-AI\pacman3\search>python pacman.py
Traceback (most recent call last):
 File "pacman.py", line 679, in <module>
   args = readCommand( sys.argv[1:] ) # Get game components based on input
 File "pacman.py", line 567, in readCommand
   import graphicsDisplay
 File "C:\Udacity-AI\pacman3\search\graphicsDisplay.py", line 15, in <module>
   from graphicsUtils import *
 File "C:\Udacity-AI\pacman3\search\graphicsUtils.py", line 294, in <module>
   def keys_pressed(d_o_e=tkinter.tkinter.dooneevent,
AttributeError: module 'tkinter' has no attribute 'tkinter'
```

> I was able to get the pacman code run and fix the tkinter issues.  I had to replace all "Tkinter.tkinter"  in graphicsUtils.py to "tkinter._tkinter", Also dooneevent is no longer in tkinter._tkinter, but is still a member of the Tk (aka root) object.

>any code for dooneevent was changed `asd_o_e=lambda arg: _root_window.dooneevent(arg),
       d_w=tkinter._tkinter.DONT_WAIT`

>`d_o_e=lambda arg: _root_window.dooneevent(arg),
       d_w=tkinter._tkinter.DONT_WAIT`

**Comment by msmcguiver** [comment]
it looks like there's a new zip file on the site that addresses these issue, but it's in the supporting materials section.  the instructions still contain a link to an older zip file that throws the above errors.
