### ISSUE TITLE
Search 22. Search Comparison Quiz issue

### ISSUE THREAD

**Issue by Spikhalskiy** [udacity/aind-issue-reports#22]
Hi, this quiz audio states that I need to fill an order of checking nodes for each algorithm. And next video for Quiz solving contains a solution for this part of the quiz. But quiz itself has only checkboxes related to optimality question and nothing about nodes order. So, quiz looks incomplete and inconsistent with what should we have from the audio.

**Comment by danainschool** [comment]
thank you!  creating internal ticket on this [J693]
