### ISSUE TITLE
Udacity Mentor Dashboard Issue

### ISSUE THREAD

**Issue by hhprogram** [udacity/aind-issue-reports#227]
Within reviewer dashboard and you go into your project review ratings. You can see the rating your review got from the student correctly. Except if you happen to mouse over the stars, the rating just goes to the star your mouse is over - and it makes it seem like you can choose the star rating which is confusing.

**Comment by letyrodridc** [comment]
Hi @hhprogram , This waffle board is for AI Nanodegree errors related. For bugs in mentors, check the Mentors slack. This is a separated team. Thanks.
