### ISSUE TITLE
Conda environment setting instruction

### ISSUE THREAD

**Issue by 921kiyo** [udacity/aind-issue-reports#25]
Bash stops working after deactivate Conda Environment. If this is happening for all students who use Windows, the explanation in the link should be added in the instructions. 
https://discussions.udacity.com/t/windows-10-bash-stops-working-after-deactivate-conda-environment/221977/3

**Comment by danainschool** [comment]
If you are using Windows, you can do all Conda from a simple Windows terminal.  Can you point me to the lesson segment that is leading you to a Bash window?
