### ISSUE TITLE
Implement eliminate()

### ISSUE THREAD

**Issue by paynelsam** [udacity/aind-issue-reports#26]
To prevent errors, the "starting" code should have
"return values" added in the function body.

**Comment by paynelsam** [comment]
Last quiz in Lesson 3: Section 5: "Strategy 1: Elimination"

**Comment by danainschool** [comment]
adding to internal list

**Comment by danainschool** [comment]
the docstring already includes a description of what should be returned.  The exact implementation and name of the variables are left to the student to provide.
