### ISSUE TITLE
Lesson 12.7 - quiz - right answer is rejected

### ISSUE THREAD

**Issue by morganel** [udacity/aind-issue-reports#35]
I tried with .3125 and 5./16 and both answers were rejected.

**Comment by morganel** [comment]
Lesson 12.8 - quiz is also broken. The answer .55 does not pass.

**Comment by morganel** [comment]
I meant lesson 12.9 instead of 12.8 (Dependence).
The quiz is also broken for lesson 12.11 (weather): .2 is rejected.

Lesson 12.16 - Cancer 3 Part 2 Quiz: .001 is rejected but 0.001 passes

**Comment by danainschool** [comment]
thank you - these have been corrected!
