### ISSUE TITLE
Lesson 14.3 - Enumeration 1 (wrong answer)

### ISSUE THREAD

**Issue by morganel** [udacity/aind-issue-reports#38]
According to the image in the video, P(+b) = 0.01 But the solution in 0.001.

If P(+b) = 0.01, the product of the five terms is 1.197e-05. But the solution is 1.197e-06

**Comment by danainschool** [comment]
Thank you.  The slide is wrong.  P(+b) = 0.001  .  An internal ticket to fix the slide in this video and the following has been initiated. [J721]
