### ISSUE TITLE
Lesson 14.13 - no content after minute 1:33 in video

### ISSUE THREAD

**Issue by morganel** [udacity/aind-issue-reports#40]

**Comment by morganel** [comment]
Lesson 14.14 also stops at 1:44 (nothing happens until the end of the video at 2:15)

**Comment by morganel** [comment]
Lesson 14.16 stops at 1:29 (out of 1:59)

**Comment by danainschool** [comment]
Thank you - an internal ticket has been created to fix this. [J726, J727, J730]
