### ISSUE TITLE
Quiz coin flip 5

### ISSUE THREAD

**Issue by amrutapj27** [udacity/aind-issue-reports#42]
three quizzes in chapter 'Probability' are not accepting correct answers.

First is video 5 Coin flip 5
Second is video11 Weather 
Third is video 9 Dependence

**Comment by ivanlflj** [comment]
Same thing with me.

**Comment by danainschool** [comment]
Thank you:  Re-entered the regex answers and these are working now.  I'm closing the ticket but please let me know if you still have problems.

**Comment by amrutapj27** [comment]
Yes. It is working now. Thanks a lot!
