### ISSUE TITLE
Bayes nets lesson doesnt accept right answers

### ISSUE THREAD

**Issue by kvr777** [udacity/aind-issue-reports#44]
especially Explaining Away, Explaining Away 2, Explaining Away 3,

**Comment by danainschool** [comment]
These appear to be working correctly.  Please note that the instructions require rounding for the answers.

**Comment by kvr777** [comment]
Dear Dana,

The lesson "Explaning Away" accepted my answer, when I just resubmitted it.
But "Explaning Away 2 " didnt. Please see screenshot below:

[image: Inline image 1]

The same attitude with third exercise:

[image: Inline image 2]

**Comment by danainschool** [comment]
The answer to #2 is 0.0185 or .0185   
The answer to #3 is 0.0833 or .0833
I am not having problems with these. Also I can't see the images you attached.  Can you try it again?
