### ISSUE TITLE
Typo on slides in video 11.12 (Classical Planning 1)

### ISSUE THREAD

**Issue by jdoepfert** [udacity/aind-issue-reports#45]
In the "Planning" lesson, part 12 (t=4:00), the "At" operator, which in this case tells me that the plane p is in airport x, is represented as "A +" . Probably someone confused a "t" with a "+".

see https://discussions.udacity.com/t/classical-planning-1-bug-in-slides/227600

**Comment by danainschool** [comment]
thank you - internal ticket created (J856)
