### ISSUE TITLE
Bad Screen shot on enumeration quiz - Inference Bayes Net

### ISSUE THREAD

**Issue by amrutapj27** [udacity/aind-issue-reports#46]
A student has reported below issue:
While the video leading up to this quiz shows a probability for P(+b)=0.001, the final screen shot after the video plays shows P(+b)=0.01. Very confusing when answering the questions:

Chapter Inference in Bayes Net: Quiz 3 Enumeration.

At the end of the video, value of P(B) has shown to be changed somehow from 0.001 to 0.01.

**Comment by danainschool** [comment]
Thank you.  The video is correct, but the final thumbnail is wrong.  An internal ticket has been created. (J857)
