### ISSUE TITLE
Arad not in explored list

### ISSUE THREAD

**Issue by amrutapj27** [udacity/aind-issue-reports#47]
Search and optimization: search video 9:
On the tree view, explored nodes are surrounded by pink box, frontier by green box and unexplored nodes by blue box. However, node A (Arad) is not surrounded by pink box though it is already explored. Is there any special reason for treating Arad differently? Video time stamp around 2:19

**Comment by danainschool** [comment]
A note has been added.  There is a transition in the discussion in this video between tree search, where explored notes are not tracked, to graph search, where they are.
