### ISSUE TITLE
Exploring Oradea even already explored

### ISSUE THREAD

**Issue by amrutapj27** [udacity/aind-issue-reports#48]
This is regarding chapter Search and Optimization : Search video 20 (Quiz: Uniform Cost Search 4). In this video, node Oradea with path 146 was explored  although it was previously explored and removed from the frontier. Ideally this video should only consider the exploration of current frontier nodes that are Fagaras, Rimnica Vilcea and Lugoj.

**Comment by napratin** [comment]
Recommend splicing out Uniform Cost Search 5, 00:32-00:48 ("the cheapest path...looking on the frontier"), so it should resume with 00:49-onwards ("the cheapest now is here at 299...").

Also, to make the rest of the animation consistent, the brown highlight from Oradea -> Sibiu that is drawn at 00:37 needs to be removed (throughout the remainder of the animation).

**Comment by danainschool** [comment]
added to video ticket [J960]
