### ISSUE TITLE
3.4 cross(s, t)

### ISSUE THREAD

**Issue by sudowork** [udacity/aind-issue-reports#5]
> We'll start by writing a helper function,`cross(s, t)`, which, given two strings — `s` and `t` — will return the list formed by all the possible concatenations of a letter in `s` with a letter in `t`.

Based on the code, the above should probably read:
> We'll start by writing a helper function, `cross(a, b)`, which, given two strings — `a` and `b` — will return the list formed by all the possible concatenations of a letter `s` in string `a` with a letter `t` in string `b`.

There was also a missing space. I also clarified the distinction between the variables slightly.

**Comment by dhruvp** [comment]
Fixed! Also added an example for further clarity.
