### ISSUE TITLE
Grading bug in "Quiz: Conditional Independence 2" of "Bayes Nets" lesson

### ISSUE THREAD

**Issue by jdoepfert** [udacity/aind-issue-reports#50]
The grader only allows the answer 0.2301, whereas a more accurate answer is 0.2304, see calculation below.

P(T2+,T1+) = 0.01 * 0.9 * 0.9 + 0.99 * 0.2 * 0.2 = .0477
P(T2-,T1+) = 0.01 * 0.9 * 0.1 + 0.99 * 0.2 * 0.8 = .1593

P(T1+) = P(T2+,T1+) + P(T2-,T1+)
P(T1+) = .0477 + .1593 = .2070

P(T2+|T1+) = P(T2+,T1+)/P(T1+)
P(T2+|T1+) =  .0477 /.2070 = .23043478260869565217

**Comment by danainschool** [comment]
Note that the quiz asks for the answer to 3 decimal places, so the answer of 0.230  is accepted.
