### ISSUE TITLE
e, a should be +e, +a in requested formula - Lesson 14 - Inference in Bayes Nets - 3. Quiz Enumeration

### ISSUE THREAD

**Issue by letyrodridc** [udacity/aind-issue-reports#51]

**Comment by letyrodridc** [comment]
For example, P(e) should be P(+e).

And all e, a should be +e, +a (in the requested formulas)

**Comment by danainschool** [comment]
The notation in the video is correct. In these cases, the P(e) and P(a|+b, e) and P(+j|a), etc. refer to the probability "for all a" and "for all e", meaning whether they are true or false.  The quiz question then asks for a computation for the case when e and a are both true.  However the entire enumeration equation is correct for P(+b | +j, +m)
