### ISSUE TITLE
Suggestion for Isolation Project Readme

### ISSUE THREAD

**Issue by tommulkins** [udacity/aind-issue-reports#53]
Please consider adding a reference to isolation.py's Board class methods.  A recommendation for students to read and comprehend the methods should be a suggested practice at the start as well. :)

**Comment by tommulkins** [comment]
Just want to add that I think the reference should be placed in the README.md.

**Comment by cgearhart** [comment]
Noted. We'll add a note to the README, but I'm not sure that's a good place for a full reference to the Board class -- it's a very long document already. I'll see about providing more standardized reference documentation for that class.

**Comment by tommulkins** [comment]
Thanks for considering, Chris.  I agree the current README is substantial.  Perhaps a Board README that essentially summarizes the functions(taken from the comments) from isolation.py.  The original README could suggest the student also review the Board README file to familiarize oneself with its helper functions.

**Comment by tommulkins** [comment]
I wouldn't mind lending a hand with this also if it could help.  My hands are full with the final projects but after that I could devote some time to it.

**Comment by cgearhart** [comment]
The latest update to the project includes a reference to the board class. https://github.com/udacity/AIND-Isolation/tree/master/isolation

Feel free to make a bug report or pull request in the AIND-Isolation repository if you'd like to see anything changed!
