### ISSUE TITLE
Lesson 11 Part 20 Video missing ^ (and) symbol?

### ISSUE THREAD

**Issue by ltfschoen** [udacity/aind-issue-reports#54]
In the video [Lesson 10 Part 20 Video at 3:14](https://www.youtube.com/watch?time_continue=194&v=mfu0jXFNHYM), the lecturer says "... **and** the action is not an unload", however the `^` symbol is not shown just between `(In(c,p,s)` and `a != Unload(c,p,x))`

Refer to this discussion post https://discussions.udacity.com/t/part-20-video-missing-and-symbol/234494

**Comment by ltfschoen** [comment]
I don't know how to add a description... Issue refers to AIND Lesson 11.  

In the video Lesson 10 Part 20 Video at 3:141, the lecturer says "... and the action is not an unload", however the ^ symbol is not shown just between (In(c,p,s) and a != Unload(c,p,x))

Refer to this discussion post https://discussions.udacity.com/t/part-20-video-missing-and-symbol/234494

**Comment by danainschool** [comment]
Thank you - creating an internal video ticket [J962]
