### ISSUE TITLE
Lesson 13 Part 15 typo in Bayes Networks definition

### ISSUE THREAD

**Issue by ltfschoen** [udacity/aind-issue-reports#56]
In [Lesson 13 Part 15 at 0:08](https://youtu.be/MRSpOhS-eXM?t=8s) the slides state when defining Bayes Networks that they _"define probability distributions over graphs **or** random variables"_.

It should instead state: _"define probability distributions over graphs **of** random variables"_.

(i.e. using the word **of** instead of **or**)

[Link to to discussion where confirmed](https://discussions.udacity.com/t/lesson-13-part-15-typo-in-bayes-networks-definition/238137)

**Comment by danainschool** [comment]
Thank you -added internal ticket [J989]
