### ISSUE TITLE
Lesson 13 Part 20 typo

### ISSUE THREAD

**Issue by ltfschoen** [udacity/aind-issue-reports#57]
In [Lesson 13 Part 20 at 0:18](https://youtu.be/-oRV6IpkX8Y?t=18s) the bottom of the slides show (and it is also stated verbally) that _"E is **not independent** of C | D"_, which appears to contradict the solution that we came up with in Lesson 13 Part 19 where we came up with the answer to whether E is independent of C given D (i.e.  `E ⊥ C | D`) as being YES (note that this answer is shown in the middle of the screen in both the Lesson 19 and 20 slides).

In this discussion post](https://discussions.udacity.com/t/lesson-13-part-20-typo-notation-clarification/238160) some alternative approaches are suggested

**Comment by danainschool** [comment]
thank you - agree he is saying "now" but it was misinterpreted; internal ticket submitted [J990]

**Comment by ltfschoen** [comment]
@danainschool unfortunately I didn't pick that up. I actually rely a lot on the video Closed Captions, which may have influenced my interpretation.

**Comment by danainschool** [comment]
It was hard to understand and I'm sure you are not the only one that was misled.  Thanks for catching it.  We will get both the video slide and the subtitles corrected.
