### ISSUE TITLE
Lesson 14 Part 10 opportunity to shorten video by 30%

### ISSUE THREAD

**Issue by ltfschoen** [udacity/aind-issue-reports#58]
In [Lesson 14 Part 10 video between 0:19s and the end at 0:28s](https://youtu.be/AWPzJsQ7KoA?t=19s) there is no sound, so the video could be shortened by 30%, but I suspect there was supposed to be audio instructing students to answer the quiz questions

**Comment by danainschool** [comment]
Nothing is missing here... its just an awkward silence - added a ticket [J991]
