### ISSUE TITLE
Lesson 14 Part 11 opportunity to shorten video by 50%

### ISSUE THREAD

**Issue by ltfschoen** [udacity/aind-issue-reports#59]
In [Lesson 14 Part 11 video between 0:17s and the end at 0:30s](https://youtu.be/ESweiuu8eKI?t=17s) there is no sound, so the video could be shortened by nearly 50%

Also, the [video with the answer](https://www.youtube.com/watch?v=Gr8Es-E5Gc0) to this quiz could be shortened by 25% by removing from 0:15 and 0:21 where there's no sound too

**Comment by danainschool** [comment]
added ticket [J992]
