### ISSUE TITLE
4.7 Monty Hall Problem VDO

### ISSUE THREAD

**Issue by korakot** [udacity/aind-issue-reports#6]
at time 0.50
P(CarA)=P(CarB)=P(CarC)=1
should be
P(CarA)+P(CarB)+P(CarC) = 1

**Comment by dhruvp** [comment]
@AaronGross could you take a look at this please?

**Comment by AaronGross** [comment]
@dhruvp Could I get a direct link to the video so I make sure I am correcting the right one?

**Comment by kkweon** [comment]
Lecture "7. Monty Hall problem: Explained"
The youtube video link: https://youtu.be/4q2DHERgVdg?t=56s

**Comment by napratin** [comment]
Noted in media request sheet.
