### ISSUE TITLE
Lesson 15 Part 23 Quiz - insufficient input field width

### ISSUE THREAD

**Issue by ltfschoen** [udacity/aind-issue-reports#62]
The input boxes where we are asked to enter our solutions are only wide enough to fit (and view) one character because of a CSS value `padding: 10px;` that has been unnecessarily applied (i.e. if we want to enter a probability of .8 in the input box you can only see either ., or 8 depending on where you scroll horizontally, which is annoying for students. 

This issue is apparent for students when answering many other Quizzes, not just this one

As a quick fix, I just ran following JavaScript code in Chrome Dev Tools to fix the issue, but a long term fix would definitely be helpful:
```
var list, index;
list = document.getElementsByClassName("text-input-widget--text-input--4-Mx-");
for (index = 0; index < list.length; ++index) {
    list[index].setAttribute("style", "padding: 2px; width: 100%; text-align: center; border: 2px solid #D9A3CC; background-color: #FFE6F9; border-radius: 15px; font-weight: bold; font-size: 12px;");
}
```

**Comment by danainschool** [comment]
Hi - that sounds extremely annoying, but I can't duplicate the issue.  Is this the ""We": Transition Probabilities Quiz" ? What browser are you using?

**Comment by ltfschoen** [comment]
Yes, it's related to Lesson 15 23. Quiz: "We": Transition Probabilities Quiz.

I'm using a 13 inch Mac with OSX El Capitan v 10.11.5. The issue appears to be apparent on the latest version of Google Chrome, Firefox, and Safari. I haven't tried it on Internet Explorer or others, but a convenient tool that I'm aware of that's useful for cross-browser compatibility checking is [BrowserStack](https://www.browserstack.com/).

Using the latest Google Chrome Version 57.0.2987.133 (64-bit) with the browser window expanded as much as possible and after collapsing the Udacity side-menu fits a maximum of 2.2 characters in input field. If I open the Udacity side-menu I can fit ~1.8 characters in the input field 

Repeating the same for the latest Safari 9.1.1, I can fit a maximum of 2 characters in the input field.

Repeating the same for the latest Firefox 49.0.2, I can fit a maximum of 2 characters in the input field, and with the Udacity side-menu open it reduces and I can only fit 1.8 characters in the input field.

If the browser window is reduced in size then the amount of characters you can fit reduces too.

The quick fix in my opinion would be to to reduce the padding of all the input boxes for the quiz to a maximum of `padding: 2px;`

To clarify my earlier statement of "This issue is apparent for students when answering many other Quizzes, not just this one", I just checked and I actually haven't found any other Quizzes in the AI Nanodegree course so far that also has this issue, but I have noticed it perhaps once before, unfortunately I can't recall where.

**Comment by danainschool** [comment]
creating ticket [J999]

**Comment by napratin** [comment]
Thanks for reporting and trying it out in different browsers! I found the same results - about 1.5-2 characters, plus a period.

Closing this for now, since we do not have direct control over CSS from our content authoring tools, but I've filed a follow-up issue internally with our Engineers [EXP-3182].
