### ISSUE TITLE
Lesson 15 Part 41: Segmentally Boosted HMMs - former name mentioned, no link provided

### ISSUE THREAD

**Issue by ltfschoen** [udacity/aind-issue-reports#67]
In [Lesson 15 Part 41 Segmentally Boosted HMMs between 1:22 and 1:25s](https://youtu.be/4WVv1qPm7js?t=1m24s) Thad verbally mentions the Georgia Tech Gesture Toolkit. However a link to the Georgia Tech Gesture Toolkit is not provided on the Lesson 15 Part 42 SBMM Resources page.

Also, when I searched the internet I found [this webpage](https://wiki.cc.gatech.edu/ccg/projects/gt2k/gt2k) of the "Georgia Tech Gesture Toolkit" (GT2k), which states that it this is the **former** name it was referred to, and that it's new name is now "**Gesture and Activity Recognition Toolkit (GART)**", and that GART utilises the HTK (Hidden Markov Toolkit). Noting that HTK was referenced earlier in Lesson 15 Part 31 Readings on HMMs.

**Comment by danainschool** [comment]
internal ticket created [J998]

**Comment by napratin** [comment]
Links added to resources page. Thanks, @ltfschoen!
