### ISSUE TITLE
3.10 Wrong function name (solve/search)

### ISSUE THREAD

**Issue by morganel** [udacity/aind-issue-reports#7]
In "Solving a Sudoku with AI" lesson "10. Coding the solution" - 

We are asked to create a "solve" function but the automated grader expects a function names "search" instead. (quiz works after renaming function from solve to search)

Traceback (most recent call last):
  File "vm_main3.py", line 47, in <module>
    import main
  File "/tmp/vmuser_citgjbvpnf/main.py", line 2, in <module>
    import studentMain
  File "/tmp/vmuser_citgjbvpnf/studentMain.py", line 7, in <module>
    if function.search(grid) == solution:
AttributeError: 'module' object has no attribute 'search'

**Comment by morganel** [comment]
Seems fixed now

**Comment by dhruvp** [comment]
Great. Thanks for the heads up @morganel!
