### ISSUE TITLE
no subtitles

### ISSUE THREAD

**Issue by zhangjun9709030** [udacity/aind-issue-reports#75]
No subtitles in the 12.Classical Planning1 and 20.Situation Calculus 2 in the project Impletment a planning search.I hope to solve as soon as possible, because it seriously affected my study. Thanks!

**Comment by zhangjun9709030** [comment]
there is  the problem in the 4. Quiz: Sensorless Vacuum Cleaner Problem, too

**Comment by danainschool** [comment]
I am able to see subtitles for these sections.  However I did notice that they did not automatically show up.  Using the settings machine wheel in the lower right, I was able to turn them on and they appeared as usual.  Can you tell me if you are able to turn them on this way?

**Comment by zhangjun9709030** [comment]
Thank you for your answer！In the lower right, I only see four icons, namely, speed control, subtitle control, sound control and full-screen control. There is only an option in the subtitle control of the three sections, the option is none.But there are two options in the subtitle control of other sections, the options are none and English, so I can choose English. By the way, I study this course in Beijing, China.

**Comment by danainschool** [comment]
I've referred this to our video department with an internal ticket. [J1060]

**Comment by zhangjun9709030** [comment]
The problem has not yet resolved, which affect the progress of my study, and can you tell me when will the problem be resolved?

**Comment by cgearhart** [comment]
Reported resolved Jul-17
