### ISSUE TITLE
Lesson 7: Video 13

### ISSUE THREAD

**Issue by jamesandersen** [udacity/aind-issue-reports#77]
The audio indicates that Peter Norvig selected the next step in the BFS but the video doesn't actually show what he selected and we're expected to know for the quiz

**Comment by danainschool** [comment]
In the video, two of the three arrows at the end fade, leaving Fagaras as the selection.  The final thumbnail is not showing this final picture though, so it is confusing when you try to do the quiz after watching.  I am putting in an internal ticket to set a thumbnail from the final visual. [J1161]
