### ISSUE TITLE
Typo on "Optimizers in Keras"

### ISSUE THREAD

**Issue by philoniare** [udacity/aind-issue-reports#83]
Link: https://classroom.udacity.com/nanodegrees/nd889/parts/16cf5df5-73f0-4afa-93a9-de5974257236/modules/6124bd95-dec2-44f9-bf3b-498ea57699c7/lessons/47f6c25c-7749-4a02-b807-7a5b37f362e8/concepts/ff0ab4d8-5441-4d00-baa3-88735b503b76

Typo: [link],(https://keras.io/optimizers/)

The Markdown link syntax doesn't get applied because of the comma

**Comment by cgearhart** [comment]
Fixed. Thanks!
