### ISSUE TITLE
Term 1 - Project Planning - Missing ^

### ISSUE THREAD

**Issue by miguelusque** [udacity/aind-issue-reports#87]
In the video, at position 1:16 (https://youtu.be/whU-c3lrR2Y?t=1m16s), there is a missing ^ symbol in the EFF, between the first and the second line:
On(t,b) ^ Blank(a)       ^   <-- This is the missing 'and'.

**Comment by cgearhart** [comment]
Thanks! Internal ticket generated. [J1292]

**Comment by miguelusque** [comment]
My pleasure!
