### ISSUE TITLE
Term2 L03E20 - There is an = instead -

### ISSUE THREAD

**Issue by letyrodridc** [udacity/aind-issue-reports#88]
In this video, the formula seems wrong:
https://youtu.be/nV1W7oQOlkU?t=15

it says
log(0.6)= - log(0.2) - log(0.1) - log(0.7)=4.8

instead of
-log(0.6) - log(0.2) - log(0.1) - log(0.7)=4.8

The same with the other formula.

**Comment by cgearhart** [comment]
Which lesson did this video come from?

**Comment by letyrodridc** [comment]
Term2 Lesson 3 Item 20

**Comment by letyrodridc** [comment]
Logistic Regression

**Comment by cgearhart** [comment]
Thank you! Internal ticket generated. [J1386]
