### ISSUE TITLE
T1 Sudoku elimination - Quiz bug

### ISSUE THREAD

**Issue by nieves-abalos** [udacity/aind-issue-reports#89]
My code generates a different solution in local than in udacity quiz, and sometimes I get "Looks good" and others "Something went wrong".

The code is:
```
for box in values.keys():      
     if len(values[box])==1:
            #then eliminate that number in peers
            for peer in peers[box]:
                values[peer] = values[peer].replace(values[box],"")
    return values
```
And the result is:
```
   45    4578    3   |   9      2      14  |   6     5789    57  
   9    24678    47  |   3      47     5   |   78    278     1   
   25    257     1   |   8      79     6   |   4    23579   2357 
---------------------+---------------------+---------------------
  345    345     8   |   1     3456    2   |   9    34567  34567 
   7    123459   49  |   59   34569    4   |   1    13456    8   
  1345  13459    6   |   7     3459    8   |   2     1345   345  
---------------------+---------------------+---------------------
  134    1347    2   |   6      8      9   |   5     1478    47  
   8     1467    47  |   2      5      3   |   17    1467    9   
   6      69     5   |   4      1      7   |   3     268     26  
```
instead of the solution provided in the quiz.

I report this as seen in https://discussions.udacity.com/t/how-to-report-a-quiz-bug-regarding-elimination-problem/242120 (I cannot find the issue here)

**Comment by cgearhart** [comment]
Looks like this was caused by unordered enumeration of values.keys() creating additional cells that could be eliminated (specifically the 1 revealed in E7 can then be used to eliminate the ones in the right-middle 3x3 block). I modified the test case so that order doesn't matter, because none of the eliminated cells have only one value left.
