### ISSUE TITLE
T1 - Project 2: Game Playing Agent has wrong instructions

### ISSUE THREAD

**Issue by osanseviero** [udacity/aind-issue-reports#91]
In the project instructions in the classroom this is mentioned: "The get_move() method should call either minimax or alpha-beta depending on the method selected. Iterative deepening should be used if the iterative flag is set.". This instruction is deprecated. Iterative deepening is only used in the alpha beta get_move function. The project code was changed from that specification.

**Comment by cgearhart** [comment]
Thanks, it should be fixed now.
