### ISSUE TITLE
program submit manager issue

### ISSUE THREAD

**Issue by ghost** [udacity/aind-issue-reports#92]
Hi, I have tried all the methods provided by the forum, but I fail to submit it. In addition, I am not allowed to submit any questions again without the next 12 hours. Hence, I have no idea how to fix it. For more details, you can find the questions I post in the links:
https://discussions.udacity.com/t/project-assistant-install-incorrect/249774/21

In addition, I can't use the google account method because I am a hotmail user.

**Comment by cgearhart** [comment]
You can still use the jwt authentication method; the reference to Google authentication only means that folks who use that method of signing in to Udacity _must_ use jwt authentication. You should be able to use either method.

I'll be happy to help you work out this issue, but it isn't really an issue with the PA. Feel free to DM me on Slack (I responded to your earlier comment there on the same topic).
