### ISSUE TITLE
Term2 Lesson 2 Deep NN Other activation function says 0 < 0

### ISSUE THREAD

**Issue by letyrodridc** [udacity/aind-issue-reports#96]
On the video, there is a partitioned function that in the conditions says x >= 0  , but in the other part says 0 < 0 instead of x < 0.

Classroom lesson:
https://classroom.udacity.com/nanodegrees/nd889/parts/16cf5df5-73f0-4afa-93a9-de5974257236/modules/6124bd95-dec2-44f9-bf3b-498ea57699c7/lessons/47f6c25c-7749-4a02-b807-7a5b37f362e8/concepts/79a26389-34e8-4b3b-9cae-29f6ed792ba6

**Comment by cgearhart** [comment]
Thanks -- internal ticket generated J1551

**Comment by cgearhart** [comment]
Fixed
